### ISSUE TITLE
Database exception: Timeout expired

### ISSUE THREAD

**Issue by adrianir** [afisd/jovice#10]
Assalammualaikum bro, i've found this timeout today? it is same case like before?

> 16/04/19 13:51:01.577|JOVICE|Database exception: Timeout expired.  The timeout p
> eriod elapsed prior to completion of the operation or the server is not respondi
> ng., SQL: delete from MEInterface where MI_ID in ('xVJctE!?fxq(9S-ZuKe<','xvs,HO
> _$*B;`t6Ns4.vc','xvs<iyWY74t)rf4@rI,0','xvvMgcqz[n|b2D*u:t>6','XW$6u4ZVV}F;)T?eI
> W!U','xW+SI!#[gtL-iP[f!FQ9','XW;u7*/W|G?RY;1~1Ws:','XW`dilwr`Gx]`#cg0J`9','XW4w~
> =jtz=*.{V~1~V)$','XW7oM[FKim|-N+I-ib<*','xwB[hFJI>H$vr5!sS,pD','xwNA;=g@LWAjNdu7
> -9A+','XwozS>`f?DWVGy](?~ZW','XWPU08IRUyFB#6^JB:rY','XX;.Ta98S8L*22PBXg1T','xx@A
> (L4H*VB)fP!0-FHf','xX^kA~/L.`>_FiU)_YY=','XXjJdLCldHWu.;i@g8u^','XXZ@F,CT,QPN1[T
> _2J>N','xY(}+;s#p.1)fh`r6Y(g')
> 16/04/19 13:51:01.578|ME2-D2-CKA|Exception while executing execute, retrying...
> 16/04/19 13:51:35.485|JOVICE|Database exception: Timeout expired.  The timeout p
> eriod elapsed prior to completion of the operation or the server is not respondi
> ng., SQL:
> select top 500 a.MI_ID, b.MI_ID as MI_MI
> from
> MEInterface a with (NOLOCK), MEInterface b with (NOLOCK)
> where a.MI_Name like '%.%' and a.MI_MI is null and a.MI_NO = b.MI_NO and
> b.MI_Name not like '%.%' and a.MI_Name like b.MI_Name + '.%'

**Comment by afisd** [comment]
Solved in Build 6.
