### ISSUE TITLE
Table MEINTERFACE cannot handle 2 MI_MC ID (Huawei)

### ISSUE THREAD

**Issue by adrianir** [afisd/jovice#18]
For example:

<ME2-D4-MPH>display  current-configuration interface Eth-Trunk1.132
#
interface Eth-Trunk1.132
 vlan-type dot1q 132
 description GBL-PEGBL-MPH-OLT-BITRATEX
 mtu 1986
 mpls l2vc 172.31.63.3 1955563834
 mpls l2vc 172.31.63.42 1955573834 secondary
 trust upstream default
 trust 8021p
 user-queue cir 20480 pir 20840 inbound
 user-queue cir 20480 pir 20480 outbound
 statistic enable

it has two MC_ID with two different VCID on each, on query like this:

MC_ID                                 MC_VCID
BY9IIa1PqWN@j_[d3IGl	    1955573834
$:,sR677FZJ@fjGbGN>U  1955563834

But in MEINTARFACE table only have 1 MI_MC which refer to one of them
Please add two different MC_ID on MEINTARFACE table, thank you so so so much...

**Comment by afisd** [comment]
I purpose to change the Huawei's MPLS L2VC group name (from previously `VCID_GROUP`) into `interface_GROUP`. This will merge two (or more) separated circuit into single circuit which also merge their associated peer.

**Comment by afisd** [comment]
Added the fix on commit fe65dcd4a337273db1c6737deb6f5c44dc1daa64
