### ISSUE TITLE
IP WAN on table peinterfaceip (pp_ip=pi_id) count double

### ISSUE THREAD

**Issue by adrianir** [afisd/jovice#19]
For Example, SID: 4702184-0021267631

on NE:

RP/0/RSP0/CPU0:PE2-D2-JT2-INET#show running-config interface Gi0/0/1/0.3514
Tue Apr 18 11:52:46.408 GMT
interface GigabitEthernet0/0/1/0.3514
 description ASTINET BB BADAN PERTANAHAN NASIONAL JL KEMBANGAN RAYA JAK BAR (DOMESTIK) SID 4702184-0021267631
....
 ipv4 address 192.168.122.61 255.255.255.252
....
RP/0/RSP0/CPU0:PE2-D2-JT2-INET#show running-config interface Gi0/0/1/0.3516
Tue Apr 18 11:52:50.103 GMT
interface GigabitEthernet0/0/1/0.3516
 description ASTINET BB BADAN PERTANAHAN NASIONAL JL KEMBANGAN RAYA JAK BAR (GLOBAL) SID 4702184-0021267631
 ....
 ipv4 address 192.168.122.173 255.255.255.252
....

But when i'm querying Jovice, this is the result:

PE2-D2-JT2-INET	Gi0/0/1/0.3516	3516	Astinet_Global	192.168.122.173/30
PE2-D2-JT2-INET	Gi0/0/1/0.3516	3516	Astinet_Global	192.168.122.173/30
PE2-D2-JT2-INET	Gi0/0/1/0.3514	3514	Astinet_Domestik	192.168.122.61/30
PE2-D2-JT2-INET	Gi0/0/1/0.3514	3514	Astinet_Domestik	192.168.122.61/30

But this issues did not happen in Astinet Regular or VPN IP

Pleaseee help to solve this issues, thank you Center...

**Comment by adrianir** [comment]
Upps, it happen also on Astinet Regular :

PE2-D2-JT2-INET	Gi0/0/1/0.74	Astinet-Conn	36.66.88.105/29  -r<(ujI;W,O]BN(P6#7;
PE2-D2-JT2-INET	Gi0/0/1/0.74	Astinet-Conn	36.66.88.105/29  -r<(ujI;W,O]BN(P6#7;

**Comment by adrianir** [comment]
Thanks bro, i've check and this is the result:

PE2-D2-JT2-INET	Gi0/0/1/0.74	Astinet-Conn	36.66.88.105/29

Solved

**Comment by afisd** [comment]
Closed
