### ISSUE TITLE
QoS Car in ME HUAWEI

### ISSUE THREAD

**Issue by adrianir** [afisd/jovice#20]
Hei bro, i found stuff again in ME Huawei:

interface GigabitEthernet3/1/7.3733
 vlan-type dot1q 3733
 description 4706914-0030268988 - MM_ASTINET DOMESTIK BANK JATENG Jl. Pemuda No.142 SEMARANG
 qos car cir 360000 pir 360000 cbs 18700000 pbs 18700000 green pass yellow pass red discard inbound
 qos car cir 360000 pir 360000 cbs 18700000 pbs 18700000 green pass yellow pass red discard outbound
 statistic enable

It using qos car cir like in PE Huawei, but jovice still didnt get this information... 
Could Jovice add this condition

NB: qos car cir can input into qos profile also like this

qos-profile 50M-Car
 car cir 50000 pir 50000 cbs 9350000 pbs 9350000 green pass yellow pass red discard

Thanks...

**Comment by afisd** [comment]
I added the handler on next build, it uses same method as PE Huawei

**Comment by adrianir** [comment]
Bro please add pi_pn for vrf %Astinet% in PE Huawei also... trims
