### ISSUE TITLE
Unhandled Exception: System.IO.IOException: Pipe closed

### ISSUE THREAD

**Issue by adrianir** [afisd/jovice#3]
> 16/02/28 23:06:25.869|TOPO|Commit: MI 633, MIMI 45, MIMIAGG 0, PI 0, MITOPI 0, M
> P 500
> 
> Unhandled Exception: System.IO.IOException: Pipe closed
>    at Tamir.Streams.PipedInputStream.checkStateForReceive() in D:\Projects\Share
> \Jovice.Common\Library\SharpSSH\Streams\PipedInputStream.cs:line 213
>    at Tamir.Streams.PipedInputStream.receive(Byte[] b, Int32 off, Int32 len) in
> D:\Projects\Share\Jovice.Common\Library\SharpSSH\Streams\PipedInputStream.cs:lin
> e 173
>    at Tamir.Streams.PipedOutputStream.Write(Byte[] buffer, Int32 offset, Int32 c
> ount) in D:\Projects\Share\Jovice.Common\Library\SharpSSH\Streams\PipedOutputStr
> eam.cs:line 212
>    at Tamir.Streams.CombinedStream.Write(Byte[] buffer, Int32 offset, Int32 coun
> t) in D:\Projects\Share\Jovice.Common\Library\SharpSSH\Streams\CombinedStream.cs
> :line 98
>    at Tamir.SharpSsh.SshShell.Write(Byte[] buffer, Int32 offset, Int32 count) in
>  D:\Projects\Share\Jovice.Common\Library\SharpSSH\SshShell.cs:line 128
>    at Jovice.Probe.NodeExit(String manufacture) in D:\Projects\Share\Jovice.Comm
> on\Necrow\Probe.cs:line 2047
>    at Jovice.Probe.NodeEnd() in D:\Projects\Share\Jovice.Common\Necrow\Probe.cs:
> line 2009
>    at Jovice.Probe.MEProcess() in D:\Projects\Share\Jovice.Common\Necrow\MEProbe
> .cs:line 3171
>    at Jovice.Probe.MainLoop() in D:\Projects\Share\Jovice.Common\Necrow\Probe.cs
> :line 513
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
> ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
> ontextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
> ontextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

**Comment by afisd** [comment]
Might be related to sudden disconnection from ssh server, we should change the disconnection handler logic.

**Comment by afisd** [comment]
Added solution in #2
