### ISSUE TITLE
PE2-D4-GBL-INET and PE2-D4-GBL-INET are not updated

### ISSUE THREAD

**Issue by afisd** [afisd/jovice#4]
As reported by Adrian, PE2-D4-GBL-INET and PE2-D4-GBL-INET were not updated even though issued force command to necrow.

**Comment by afisd** [comment]
Necrow should only start checking the node, if the last configuration is newer than the one that stored in the database (jovice), on Node NO_LastConfiguration.

Current command (to check last configuration) that issued to non-XR Cisco node is
> show configuration id detail

Apparently, this is incorrect for these nodes (maybe versions? revision?). We should make an exception for this special version of non-XR Cisco nodes.

**Comment by afisd** [comment]
Checked the database, for NO_LastConfiguration is null (or failed to retrieve the last configuration failed):
> select NO_Name, NO_Remark, NO_Model, NO_Version, NO_SubVersion, NO_LastConfiguration
> from Node where NO_Model <> 'ASR' and NO_Manufacture = 'CISCO' and NO_LastConfiguration is null and NO_Active = 1

returns some nodes, with versions:
12.2(18)S6
12.2(18)SXF8
12.2(25)S5
12.2(33)SRB4
12.2(33)SXH6
12.3(15a)
12.3(9c)
12.3(9e)
12.4(15)T1
12.4(6)T
12.4(7c)
12.4(7g)
12.4(7h)

**Comment by afisd** [comment]
We're going to test command in IOS version for last configuration check. If one command failed the test, just test the second one, and so on. To reduce overhead, the first command to test is the most usable command known to date: show configuration id detail, then show configuration history, then configuration date on top running configuration, then if everything fails, we're going to use show log | in Config, which is very not viable if the node aren't configured recently (because the log will besaturated by recent events like connection-disconnection, routes, etc).

**Comment by adrianir** [comment]
You are awesome dudes... great job!!
