### ISSUE TITLE
Unhandled Exception: System.Exception: Warning: This result contain exceptions

### ISSUE THREAD

**Issue by adrianir** [afisd/jovice#5]
Hai bro, i found this error message last night.. i think i never saw this alert before

> Unhandled Exception: System.Exception: Warning: This result contain exceptions
>    at Aphysoft.Common.Result.get_Item(Int32 index) in D:\Projects\jovice\Aphysof
> t.Common\Database\Database.cs:line 1005
>    at Jovice.Summary.<>c__DisplayClass7_1.<MainLoop>b__0() in D:\Projects\jovice
> \Jovice.Common\Necrow\NodeSummary.cs:line 103
>    at Jovice.Summary.SummaryEntry(String key, Dictionary`2 current, String nodeI
> D, Batch batch, TimeSpan expireTime, SummaryCallback summary) in D:\Projects\jov
> ice\Jovice.Common\Necrow\NodeSummary.cs:line 282
>    at Jovice.Summary.MainLoop() in D:\Projects\jovice\Jovice.Common\Necrow\NodeS
> ummary.cs:line 105
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
> ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
> ontextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
> ontextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

**Comment by afisd** [comment]
There are some lines before the error occurred:

> 16/03/03 17:19:36.774|PROB|Begin probing into PE2-D5-RKT
> 16/03/03 17:19:36.774|PROB|Host IP: 61.5.14.246
> 16/03/03 17:19:36.774|PROB|Manufacture: CISCO
> 16/03/03 17:19:36.774|PROB|Model: 7609-S
> 16/03/03 17:19:36.774|PROB|Checking host IP
> 16/03/03 17:19:36.874|PROB|Hostname is unresolved
> 16/03/03 17:19:36.874|PROB|Resolving by reverse host name
> 16/03/03 17:19:37.159|PROB|Hostname has changed to: PE2-D5-RKT-INET
> 16/03/03 17:19:37.944|PROB|Existing node has found, delete this node
> 16/03/03 17:19:37.944|PROB|Creating alias

Probably, it messed up with summary service (the one that calculates topology, etc). Summary service is running in parallel and should not be interfered whenever database has changed.

**Comment by afisd** [comment]
So I've come with solution to temporary stop any process/service that might interfere this, probably TopologyFinder and Summary:

```
                            if (Necrow.IsServiceSet(NecrowServices.TopologyFinder))
                                TopologyFinder.Stop();
                            if (Necrow.IsServiceSet(NecrowServices.Summary))
                                Summary.Stop();

                            while (true)
                            {
                                // wait until topologyfinder and summary stopped
                                if (TopologyFinder.IsStop() && Summary.IsStop())
                                    break;
                                else
                                    Thread.Sleep(1000);
                            }
...
                            // Start again
                            if (Necrow.IsServiceSet(NecrowServices.TopologyFinder))
                                TopologyFinder.Start();
                            if (Necrow.IsServiceSet(NecrowServices.Summary))
                                Summary.Start();
```

I will put this for build 2 this afternoon. Personally, I do not know if this will solve the problem, and because this kind of error is kinda rare (because database runtime interlocking each other by probe AND other services) we might not be confirmed the fixes any time soon. Or we can reopen this issue if something like this happened again.

**Comment by afisd** [comment]
I've seen some errors during stopping of the services, reopen the issue.

**Comment by afisd** [comment]
I removed services suspension for Topology and Summary because they're clearly not related to database error. I tried to put database exception handler and we shall wait for another error like this.
