### ISSUE TITLE
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the boun ds of the array.

### ISSUE THREAD

**Issue by adrianir** [afisd/jovice#6]
> Unhandled Exception: System.IndexOutOfRangeException: Index was outside the boun
> ds of the array.
>    at Jovice.Probe.MEProcess() in D:\Projects\jovice\Jovice.Common\Necrow\MEProb
> e.cs:line 1664
>    at Jovice.Probe.MainLoop() in D:\Projects\jovice\Jovice.Common\Necrow\Probe.c
> s:line 526
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
> ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
> ontextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
> ontextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

**Comment by afisd** [comment]
fixed in build 5.
