### ISSUE TITLE
Infinite Looping on Jovice

### ISSUE THREAD

**Issue by adrianir** [afisd/jovice#8]
> 16/04/18 11:23:37.845|ME-D2-PLM|Exception while executing execute, retrying...
> 16/04/18 11:23:42.921|JOVICE|Database exception: The DELETE statement conflicted
>  with the REFERENCE constraint "FK_MC_MECustomer". The conflict occurred in data
> base "jovice", table "dbo.MECircuit", column 'MC_MU'.
> The statement has been terminated., SQL: delete from MECustomer where MU_ID = 'B
> <GKmrDY4AUK?A8_UB0Z'
> 16/04/18 11:23:42.923|ME-D2-PLM|Exception while executing execute, retrying...
> 16/04/18 11:23:48.096|JOVICE|Database exception: The DELETE statement conflicted
>  with the REFERENCE constraint "FK_MC_MECustomer". The conflict occurred in data
> base "jovice", table "dbo.MECircuit", column 'MC_MU'.
> The statement has been terminated., SQL: delete from MECustomer where MU_ID = 'B
> <GKmrDY4AUK?A8_UB0Z'
> 16/04/18 11:23:48.098|ME-D2-PLM|Exception while executing execute, retrying...
> 16/04/18 11:23:53.236|JOVICE|Database exception: The DELETE statement conflicted
>  with the REFERENCE constraint "FK_MC_MECustomer". The conflict occurred in data
> base "jovice", table "dbo.MECircuit", column 'MC_MU'.
> The statement has been terminated., SQL: delete from MECustomer where MU_ID = 'B
> <GKmrDY4AUK?A8_UB0Z'

**Comment by afisd** [comment]
Apparently, it happened because necrow cannot delete MECustomer because it still bound to MECircuit that should not be exists in the database. I have gone through MEProbe.cs and found out that DELETE PEER and DELETE CIRCUIT wont be executed because if conditions was not correct. I will deploy the updated necrow as soon as possible.
