### ISSUE TITLE
Rate n QOS on 'PE-D1-BDS-iNET'

### ISSUE THREAD

**Issue by adrianir** [afisd/jovice#9]
After i re-probe several times, still return null on rate and QOS at PEINTERFACE with node = 'PE-D1-BDS-INET'

oo iya Fis, mau tanya tentang progres nya PE-Transit gimana ya?

**Comment by afisd** [comment]
Fixed in Build 6, there are some weirdness for interface-qos handling in non-asr cisco. The probe is now will use `show policy-map interface input brief` command by default, if it fails then use `show policy-map interface | in Service-policy_input|Service-policy_output|Ethernet|Serial` instead.
